//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab20.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        
        public int UserID { get; set; }
        [Required][MinLength(2)][MaxLength(20)]
        public string FirstName { get; set; }
        [Required][MinLength(2)][MaxLength(20)]
        public string LastName { get; set; }
        [Required][RegularExpression(@"^[A-z\@.]+$")]
        public string Email { get; set; }
        public string Phone { get; set; }
    }
}
